/**
 * Write the cross-batch analysis as a standalone Markdown report.
 *
 * Why a generator rather than a hand-written file: `reports/` is gitignored, so anything
 * saved there is disposable by design. The durable artefact is the pipeline —
 * `extract.js` -> `analyze.js` -> this — so the report can be rebuilt from `logs/` after
 * any new batch instead of drifting out of date beside the numbers it quotes.
 *
 *   node analysis/extract.js && node analysis/analyze.js && node analysis/report-md.js
 */
const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const S = JSON.parse(fs.readFileSync(path.join(HERE, 'summary.json'), 'utf8'));
const D = JSON.parse(fs.readFileSync(path.join(HERE, 'dataset.json'), 'utf8'));

const sgn = (v, d = 3) => {
  if (v === null || v === undefined) return '—';
  const s = Math.abs(v).toFixed(d);
  return parseFloat(s) === 0 ? s : (v >= 0 ? '+' : '−') + s;
};
const pct = (v, d = 1) => (v * 100).toFixed(d) + '%';

const gate = (r) => !r.isControl && (r.nTownSeats < 20 || r.invalid > 0.15);

// The control's spread, split by batch size — the correction in section 1.
const big = S.controlBatches.filter((b) => b.games >= 30).map((b) => b.lift);
const small = S.controlBatches.filter((b) => b.games < 15).map((b) => b.lift);
const span = (a) => (Math.max(...a) - Math.min(...a)).toFixed(3);
const rng = (a) => sgn(Math.min(...a)) + ' to ' + sgn(Math.max(...a));

const def = S.defense;
const out = S.outcomes;
const townTotal = out.reduce((a, o) => a + o.townWins, 0);
const gameTotal = out.reduce((a, o) => a + o.n, 0);

// Per-day curves for the three players section 3 contrasts.
const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : null);
function dayCurve(pred) {
  return [1, 2, 3].map((day) => {
    const ts = D.townTurns.filter((t) => t.day === day && pred(t));
    return ts.length >= 25
      ? { day, n: ts.length, lift: mean(ts.map((t) => t.hit - t.chance)) }
      : { day, n: ts.length, lift: null };
  });
}
const PLAYERS = [
  ['rule-based control', (t) => t.model === 'rule-based-v1'],
  ['gpt-oss:120b', (t) => t.model === 'gpt-oss:120b'],
  ['gpt-oss:20b', (t) => t.model === 'gpt-oss:20b'],
];

let md = '';
const w = (s) => (md += s + '\n');

w('# Cross-batch analysis — every finished game');
w('');
w('Generated by `analysis/extract.js` → `analyze.js` → `report-md.js` from the per-game');
w('JSON under `logs/`. Not a batch: this reads **every** finished game at once, per turn');
w('rather than per batch. Regenerate after any new run — do not edit by hand.');
w('');
w(`**Corpus.** ${S.totals.games} games · ${S.totals.sessions} sessions · ` +
  `${S.rows.length} models · ${S.totals.seatGames.toLocaleString()} seat-games · ` +
  `${S.totals.townTurns.toLocaleString()} town accusations.`);
w('');
w('Charts: `reports/charts.html`. Narrative findings with their `n`: `RESULTS.md` § 025.');
w('');
w('---');
w('');

w('## 1. The measurement floor is sampling noise, and it shrinks on schedule');
w('');
w('The rule-based control is a fixed policy — nothing about it varies between batches, so');
w('any spread it shows is pure sampling noise. That makes it a ruler for everything else.');
w('');
w(`- All ${S.controlBatches.length} batches: **${rng(S.controlBatches.map((b) => b.lift))}**`);
w(`- Batches of ≥30 games (n=${big.length}): ${rng(big)} — **span ${span(big)}**`);
w(`- Batches under 15 games (n=${small.length}): ${rng(small)} — **span ${span(small)}**`);
w('');
w('Every extreme reading this project produced came from a batch of ≤12 games. This is');
w('ordinary `1/√n` behaviour, **not an irreducible floor** as earlier entries framed it,');
w('and it prices a readable arm at ~30 games.');
w('');

w('## 2. Detection does not exist on day 1');
w('');
w('| day | town accusations | accuracy | chance | det.lift |');
w('|---|---|---|---|---|');
for (const d of S.dayRows) {
  w(`| ${d.day} | ${d.n} | ${d.acc.toFixed(3)} | ${d.chance.toFixed(3)} | **${sgn(d.lift)}** |`);
}
w('');
w(`Day 1 is *exactly* chance on n=${S.dayRows[0].n}. Mean game length is ` +
  `${(out.reduce((a, o) => a + o.meanDays * o.n, 0) / gameTotal).toFixed(1)} days, so **most ` +
  'turns behind any pooled number are day-1 turns where no evidence exists yet** — and a');
w('model whose games end fast is scored mainly on its worst-information turns.');
w('');

w('## 3. Two different competences, which pooling destroys');
w('');
w('| player | day 1 | day 2 | day 3 |');
w('|---|---|---|---|');
for (const [name, pred] of PLAYERS) {
  const c = dayCurve(pred);
  w(`| ${name} | ` + c.map((x) => (x.lift === null
    ? `— (n=${x.n}, below floor)`
    : `${sgn(x.lift)} (n=${x.n})`)).join(' | ') + ' |');
}
w('');
w('The control starts at chance and compounds hard — its policy reads an accumulating');
w('accusation and vote record, which only exists later. `gpt-oss:120b` does the reverse:');
w('real cold-read signal on day 1 where the control has none, then it fails to compound.');
w('**A single pooled score ranks these two as near-equal while they do opposite things.**');
w('');

w('## 4. Detection lift with intervals');
w('');
w('95% **cluster bootstrap over games** (2,000 resamples, fixed seed). Seats within one game');
w('are not independent — one player\'s hit is another\'s miss — so resampling seats would');
w('shrink intervals in exactly the direction that manufactures a finding.');
w('');
w('Rows failing the readability gate (fewer than 20 town seats, or `invalid` > 0.15) are');
w('marked `gated` rather than dropped: deleting them would hide a model that scores well');
w('while substituting a quarter of its moves at random.');
w('');
w('| model | town seats | games | rosters | det.lift | 95% CI | invalid | calib | gate |');
w('|---|---|---|---|---|---|---|---|---|');
for (const r of S.rows) {
  if (r.nTownSeats === 0) continue;
  const ci = r.ciLo === null ? '—' : `[${sgn(r.ciLo)}, ${sgn(r.ciHi)}]`;
  const name = r.isControl ? `**${r.model}**` : r.model;
  const g = gate(r) ? (r.nTownSeats < 20 ? '`n`' : '`invalid`') : '';
  w(`| ${name} | ${r.nTownSeats} | ${r.nGames} | ${r.nRosters} | ${sgn(r.detLift)} | ${ci} | ` +
    `${r.invalid.toFixed(3)} | ${sgn(r.calib)} | ${g} |`);
}
w('');
const lead = S.rows.find((r) => r.model === 'gpt-oss:120b');
const ctl = S.rows.find((r) => r.isControl);
w(`\`${lead.model}\` is the only model clearing zero on a real sample ` +
  `(${sgn(lead.detLift)} [${sgn(lead.ciLo)}, ${sgn(lead.ciHi)}], ${lead.nGames} games), and its`);
w(`interval **still overlaps the control** (${sgn(ctl.detLift)} [${sgn(ctl.ciLo)}, ` +
  `${sgn(ctl.ciHi)}]). So it beats chance; it is not shown to beat the policy.`);
w('');
w('Pooling a model across batches is only strictly valid for the control, whose policy is');
w('byte-identical everywhere (see `RESULTS.md` 010) — hence the roster count on every row.');
w('');

w('## 5. The defense phase helps the Mafia');
w('');
w(`${def.all.n} defenses across ${def.games} games, each resolved against the execution that`);
w('followed. Counted per defense, not from per-game rates.');
w('');
w('| defender | defenses | survived the vote | rate |');
w('|---|---|---|---|');
w(`| town | ${def.town.n} | **${def.town.survived}** | ${pct(def.town.rate)} |`);
w(`| mafia | ${def.mafia.n} | ${def.mafia.survived} | ${pct(def.mafia.rate)} |`);
w(`| all | ${def.all.n} | ${def.all.survived} | ${pct(def.all.rate)} |`);
w('');
w(`Mean defense length ${def.meanWords.toFixed(0)} words. **An accused villager handed the`);
w('floor has never once talked their way out.** The phase was added on the theory that');
w('no-right-of-reply doomed town; the reply does not save them, while a Mafia occasionally');
w('argues its way clear.');
w('');
w('**The win-rate half is confounded and stays open.** Among 10-seat games town won 4/11');
w('with the phase on against 5/84 with it off — but those arms are different rosters');
w('(hosted vs local), so it carries no causal claim. `--no-defense` at seed 7 on **one**');
w('roster is the run that settles it.');
w('');

w('## 6. The game itself is lopsided');
w('');
w('| seats | games | town wins | town rate | mean days |');
w('|---|---|---|---|---|');
for (const o of out) {
  w(`| ${o.seats} | ${o.n} | ${o.townWins} | ${pct(o.townRate)} | ${o.meanDays.toFixed(2)} |`);
}
w(`| **all** | **${gameTotal}** | **${townTotal}** | **${pct(townTotal / gameTotal)}** | |`);
w('');
w('The deficit worsens as the table grows, which follows from section 2: a bigger room');
w('means proportionally more day-1 turns, and day-1 turns carry no signal. The setup, not');
w('the models, is doing much of this — so any claim about town performance has to be read');
w(`against a ${pct(townTotal / gameTotal)} base rate.`);
w('');

w('## Confidence carries weak signal in aggregate');
w('');
w('| stated confidence | turns | accuracy | chance | det.lift |');
w('|---|---|---|---|---|');
for (const c of S.confBuckets) {
  w(`| ${c.lo.toFixed(1)}–${c.hi.toFixed(1)} | ${c.n} | ${c.acc.toFixed(3)} | ` +
    `${c.chance.toFixed(3)} | ${sgn(c.lift)} |`);
}
w('');
w('Monotonic across the three well-populated buckets, which is the weakest defensible');
w('version of "confidence means something". The `0.2–0.4` row is n=' +
  (S.confBuckets[0] ? S.confBuckets[0].n : '?') + ' and breaks the trend; do not lean on it.');
w('');

w('---');
w('');
w('### Method notes');
w('');
w('- **Intervals bootstrap games, not seats.** Resampling seats would treat correlated');
w('  observations as independent and narrow every interval.');
w('- **`det.lift` is town-only by design.** A Mafia accusing a villager is playing');
w('  correctly, so scoring it as a miss would be nonsense.');
w('- **An analysis bug that announced itself.** The first defense pass weighted each game\'s');
w('  `mafiaSurvivalRate` by that game\'s *total* defense count, mixing a mafia-only numerator');
w('  with an all-defenders denominator, and reported 7.3 mafia survivals out of 5 total. The');
w('  arithmetic being impossible is what caught it; a merely wrong-looking number would have');
w('  shipped. Same class as DEFECT 3 — a rate whose denominator went unchecked.');

const dir = path.join(HERE, '..', 'reports');
fs.mkdirSync(dir, { recursive: true });
const target = path.join(dir, 'cross-batch-analysis.md');
fs.writeFileSync(target, md);
console.log('wrote', target, '(' + md.split('\n').length + ' lines)');
